site_name: Learning Center

nav:
    - "Step 1: Getting Started": index.md
    - "Step 2: The Basics": basics.md
    - "Step 3: What Is Covered": coverage.md
    - "Step 4: Products": products.md
    - "Step 5: How to Apply": applying.md
    - "Step 6: Claims": claims.md
    - "Step 7: About PolicyMe": about.md

theme:
  name: material
  language: en
  palette:
    primary: light-blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  #features:
  #  - tabs
  favicon: images/policyme-logo-square.png
  logo: images/policyme-logo-square.png

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/policymehq
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/policymehq/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/policymehq/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/policymehq/